services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: sh -c "pnpm prisma:migrate:auth && pnpm start:dev auth"
    ports:
      - '4100:3000'
    env_file:
      - ./apps/auth/.env

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  default:
    name: picture-network
    external: true
